build:
	gcc Matriz.c -o Matriz.exe
run: Matriz.exe
	./Matriz.exe <0.in
run1: 1.c
	rm -r *.exe
	gcc 1.c -o 1.exe
	./1.exe
gexe: 1.c #gerar exe
	gcc 1.c -o 1.exe
rexe: 1.exe #rodar exe
	./1.exe
git: 
	git add .
	git commit -m "mensagem"
	git push
