run1: 1-03.c #apagar e criar exe
	rm -rf *.exe
	gcc 1-03.c -o 1-03.exe
	./1-03.exe
run2: 2-03.c #apagar e criar exe
	rm -rf *.exe
	gcc 2-03.c -o 2-03.exe
	./2-03.exe
run3: 3-03.c #apagar e criar exe
	rm -rf *.exe
	gcc 3-03.c -o 3-03.exe
	./3-03.exe
run4: 4-03.c #apagar e criar exe
	rm -rf *.exe
	gcc 4-03.c -o 4-03.exe
	./4-03.exe